# Generated by Django 4.2.3 on 2023-08-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_contact_contact_type_alter_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
