# Generated by Django 4.2.3 on 2023-08-20 15:10

import admin.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('main_photo', models.ImageField(upload_to=admin.utils.get_timestamp_path)),
                ('grounds_doc', models.CharField(choices=[('Собственность', 'Собственность'), ('Свидетельство о праве на наследство', 'Свидетельство о праве на наследство')], max_length=100)),
                ('appointment', models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Коммерческие помещения', 'Коммерческие помещения'), ('Офисное помещение', 'Офисное помещение')], max_length=100)),
                ('room_count', models.CharField(choices=[(1, '1 комнатная'), (2, '2 комнатная'), (3, '3 комнатная'), (4, '4 комнатная'), (5, '5 комнатная'), (6, '6 комнатная'), (7, '7 комнатная')], max_length=100)),
                ('layout', models.CharField(choices=[('Студия, санузел', 'Студия, санузел'), ('Классическая', 'Классическая'), ('Европланировка', 'Европланировка'), ('Свободная', 'Свободная')], max_length=100)),
                ('living_condition', models.CharField(choices=[('Черновая', 'Черновая'), ('Ремонт от застройщика', 'Ремонт от застройщика'), ('В жилом состоянии', 'В жилом состоянии')], max_length=100)),
                ('kitchen_square', models.PositiveIntegerField()),
                ('balcony_or_loggia', models.BooleanField()),
                ('heating_type', models.CharField(choices=[('Центральное', 'Центральное'), ('Автономное', 'Автономное'), ('Альтернативное', 'Альтернативное')], max_length=100)),
                ('payment_type', models.CharField(choices=[('Ипотека', 'Ипотека'), ('Мат.капитал', 'Мат.капитал'), ('Другое', 'Другое')], max_length=100)),
                ('agent_commission', models.PositiveIntegerField(choices=[(5000, '5 000 ₴'), (15000, '15 000 ₴'), (30000, '30 000 ₴')])),
                ('communication_type', models.CharField(choices=[('Звонок + сообщение', 'Звонок + сообщение'), ('Звонок', 'Звонок'), ('Сообщение', 'Сообщение')])),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('watched_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('file', models.FileField(null=True, upload_to=admin.utils.get_timestamp_path)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('layout', models.CharField(choices=[('Студия, санузел', 'Студия, санузел'), ('Классическая', 'Классическая'), ('Европланировка', 'Европланировка'), ('Свободная', 'Свободная')], max_length=100)),
                ('grounds_doc', models.CharField(choices=[('Собственность', 'Собственность'), ('Свидетельство о праве на наследство', 'Свидетельство о праве на наследство')], max_length=100)),
                ('room_count', models.CharField(choices=[(1, '1 комнатная'), (2, '2 комнатная'), (3, '3 комнатная'), (4, '4 комнатная'), (5, '5 комнатная'), (6, '6 комнатная'), (7, '7 комнатная')], max_length=100)),
                ('min_price', models.PositiveIntegerField()),
                ('max_price', models.PositiveIntegerField()),
                ('min_square', models.PositiveIntegerField()),
                ('max_square', models.PositiveIntegerField()),
                ('appointment', models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Коммерческие помещения', 'Коммерческие помещения'), ('Офисное помещение', 'Офисное помещение')], max_length=100)),
                ('payment_type', models.CharField(choices=[('Ипотека', 'Ипотека'), ('Мат.капитал', 'Мат.капитал'), ('Другое', 'Другое')], max_length=100)),
                ('condition', models.CharField(choices=[('Черновая', 'Черновая'), ('Ремонт от застройщика', 'Ремонт от застройщика'), ('В жилом состоянии', 'В жилом состоянии')], max_length=100)),
            ],
            options={
                'db_table': 'filter',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
            ],
            options={
                'db_table': 'phrase',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.BooleanField()),
                ('highlight', models.BooleanField()),
                ('big_advert', models.BooleanField()),
                ('turbo', models.BooleanField()),
                ('raise_advert', models.BooleanField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'promotion',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
                ('auto_renewal', models.BooleanField()),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
    ]
