# Generated by Django 4.2.3 on 2023-08-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
        ('builder', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='apartment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.announcement'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='highlight_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.color'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='phrase_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.phrase'),
        ),
        migrations.AddField(
            model_name='filter',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.chat'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.complex'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.gallery'),
        ),
    ]
