# Generated by Django 4.2.3 on 2023-08-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('builder', '0002_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='advert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.advert'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='highlight_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.color'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='phrase_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.phrase'),
        ),
        migrations.AddField(
            model_name='filter',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.chat'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client'),
        ),
        migrations.AddField(
            model_name='advert',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AddField(
            model_name='advert',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.complex'),
        ),
        migrations.AddField(
            model_name='advert',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.gallery'),
        ),
    ]
