# Generated by Django 4.2.3 on 2023-08-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_initial'),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='apartment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='builder.apartment'),
        ),
    ]
