# Generated by Django 4.2.3 on 2023-09-12 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 22, 57, 12, 222143, tzinfo=datetime.timezone.utc)),
        ),
    ]
