# Generated by Django 4.2.3 on 2023-08-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_announcement_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
