# Generated by Django 4.2.3 on 2023-08-13 20:28

import admin.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_chatmessage_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(null=True, upload_to=admin.utils.get_timestamp_path),
        ),
    ]
