# Generated by Django 4.2.3 on 2023-08-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_announcement_is_actual_announcement_is_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='moderation_decide',
            field=models.CharField(blank=True, choices=[('Подтверждено', 'Подтверждено'), ('Отклонено', 'Отклонено')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='moderation_status',
            field=models.CharField(blank=True, choices=[('price', 'Некорректная цена'), ('photo', 'Некорректное фото'), ('description', 'Некорректное описание')], max_length=20, null=True),
        ),
    ]
