# Generated by Django 4.2.3 on 2023-08-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_announcement_moderation_decide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='moderation_decide',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_moderated',
            field=models.BooleanField(null=True),
        ),
    ]
