# Generated by Django 4.2.3 on 2023-08-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_reason',
            field=models.CharField(choices=[('', ''), ('theft', 'Мошенничество'), ('bad_photo', 'Некорректное фото'), ('bad_description', 'Некорректное описание')], default='', max_length=100),
        ),
    ]
