# Generated by Django 4.2.3 on 2023-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_complaint_complaint_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_reason',
            field=models.CharField(choices=[('', ''), ('Мошенничество', 'Мошенничество'), ('Некорректное фото', 'Некорректное фото'), ('Некорректное описание', 'Некорректное описание')], default='', max_length=100),
        ),
    ]
