# Generated by Django 4.2.3 on 2023-08-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_announcement_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='appointment',
            field=models.CharField(choices=[('', ''), ('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Коммерческие помещения', 'Коммерческие помещения'), ('Офисное помещение', 'Офисное помещение')], default='Офисное помещение', max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='payment_type',
            field=models.CharField(choices=[('', ''), ('Ипотека', 'Ипотека'), ('Мат.капитал', 'Мат.капитал'), ('Другое', 'Другое')], default='Мат.капитал', max_length=100),
        ),
    ]
