# Generated by Django 4.2.3 on 2023-08-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_announcement_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='appointment',
            field=models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Коммерческие помещения', 'Коммерческие помещения'), ('Офисное помещение', 'Офисное помещение')], max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='condition',
            field=models.CharField(choices=[('Черновая', 'Черновая'), ('Ремонт от застройщика', 'Ремонт от застройщика'), ('В жилом состоянии', 'В жилом состоянии')], max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='grounds_doc',
            field=models.CharField(choices=[('Собственность', 'Собственность'), ('Свидетельство о праве на наследство', 'Свидетельство о праве на наследство')], max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='layout',
            field=models.CharField(choices=[('Студия, санузел', 'Студия, санузел'), ('Классическая', 'Классическая'), ('Европланировка', 'Европланировка'), ('Свободная', 'Свободная')], max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='payment_type',
            field=models.CharField(choices=[('', ''), ('Ипотека', 'Ипотека'), ('Мат.капитал', 'Мат.капитал'), ('Другое', 'Другое')], max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='room_count',
            field=models.CharField(choices=[('1', '1 комнатная'), ('2', '2 комнатная'), ('3', '3 комнатная'), ('4', '4 комнатная'), ('5', '5 комнатная'), ('6', '6 комнатная'), ('7', '7 комнатная')], max_length=100),
        ),
    ]
