# Generated by Django 4.2.3 on 2023-08-22 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0018_alter_filter_appointment_alter_filter_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='price_per_m2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='square',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filter',
            name='appointment',
            field=models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Коммерческие помещения', 'Коммерческие помещения'), ('Офисное помещение', 'Офисное помещение')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filter',
            name='condition',
            field=models.CharField(choices=[('Черновая', 'Черновая'), ('Ремонт от застройщика', 'Ремонт от застройщика'), ('В жилом состоянии', 'В жилом состоянии')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='grounds_doc',
            field=models.CharField(choices=[('Собственность', 'Собственность'), ('Свидетельство о праве на наследство', 'Свидетельство о праве на наследство')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='layout',
            field=models.CharField(choices=[('Студия, санузел', 'Студия, санузел'), ('Классическая', 'Классическая'), ('Европланировка', 'Европланировка'), ('Свободная', 'Свободная')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='payment_type',
            field=models.CharField(choices=[('', ''), ('Ипотека', 'Ипотека'), ('Мат.капитал', 'Мат.капитал'), ('Другое', 'Другое')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='room_count',
            field=models.CharField(choices=[('1', '1 комнатная'), ('2', '2 комнатная'), ('3', '3 комнатная'), ('4', '4 комнатная'), ('5', '5 комнатная'), ('6', '6 комнатная'), ('7', '7 комнатная')], default='', max_length=100),
        ),
    ]
