# Generated by Django 4.2.3 on 2023-08-23 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0019_announcement_price_announcement_price_per_m2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='apartment',
        ),
        migrations.AddField(
            model_name='promotion',
            name='announcement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='client.announcement'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
