# Generated by Django 4.2.3 on 2023-08-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_remove_promotion_apartment_promotion_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='big_advert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='highlight_color',
            field=models.CharField(choices=[('Розовый', 'Розовый'), ('Зелёный', 'Зелёный')], null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='phrase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='phrase_content',
            field=models.CharField(choices=[('Подарок при покупке', 'Подарок при покупке'), ('Возможен торг', 'Возможен торг'), ('Квартира у моря', 'Квартира у моря'), ('В спальном районе', 'В спальном районе'), ('Вам повезло с ценой!', 'Вам повезло с ценой!'), ('Для большой семьи', 'Для большой семьи'), ('Семейное гнездышко', 'Семейное гнездышко'), ('Отдельная парковка', 'Отдельная парковка')], null=True, verbose_name='Phrase'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='raise_advert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='turbo',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
    ]
