# Generated by Django 4.2.3 on 2023-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
