# Generated by Django 4.2.3 on 2023-08-26 16:17

import admin.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_promotion_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='gallery',
        ),
        migrations.CreateModel(
            name='GalleryAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=admin.utils.get_timestamp_path)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='client.announcement')),
            ],
            options={
                'db_table': 'gallery_announcement',
                'ordering': ('id',),
            },
        ),
    ]
