# Generated by Django 4.2.3 on 2023-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_remove_announcement_complex'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryannouncement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
