# Generated by Django 4.2.3 on 2023-08-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_galleryannouncement_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryannouncement',
            options={'ordering': ('-order',)},
        ),
    ]
