# Generated by Django 4.2.3 on 2023-08-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_remove_floor_schema'),
        ('client', '0028_alter_galleryannouncement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.complex'),
        ),
    ]
