version: '3.3'

services:
  web:
    build :
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn SwipeAPI.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/SwipeAPI/web/static
      - media_volume:/home/SwipeAPI/web/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/SwipeAPI/web/static
      - media_volume:/home/SwipeAPI/web/media
    ports:
      - "1337:80"
    depends_on:
      - web
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A SwipeAPI worker -l info
    volumes:
      - .:/home/SwipeAPI/web/
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A SwipeAPI beat
    env_file:
      - ./.env.prod
    depends_on:
      - celery
volumes:
  postgres_data:
  static_volume:
  media_volume:
