# Generated by Django 4.2.3 on 2023-08-12 08:01

import admin.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'benefit',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('coordinate', models.TextField()),
                ('main_photo', models.ImageField(upload_to=admin.utils.get_timestamp_path)),
                ('min_price', models.PositiveIntegerField()),
                ('price_per_square', models.PositiveIntegerField()),
                ('min_squares', models.PositiveIntegerField()),
                ('max_squares', models.PositiveIntegerField()),
                ('square_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Квартиры', 'Квартиры'), ('Офисы', 'Офисы'), ('Торговые помещения', 'Торговые помещения')], max_length=100)),
                ('level', models.CharField(choices=[('Элитный', 'Элитный'), ('Средний', 'Средний'), ('Стандарт', 'Стандарт')], max_length=100)),
                ('type', models.CharField(choices=[('Многоквартирный', 'Многоквартирный'), ('Клубный', 'Клубный(Малоквартирный)')], max_length=100)),
                ('material_type', models.CharField(choices=[('Монолитный каркас с керамзитно-блочным заполнением', 'Monolith'), ('Каркасно-панельное', 'Каркасно-панельное строительство'), ('Монолитно-панельное', 'Монолитно-панельное')], max_length=100)),
                ('perimeter_status', models.CharField(choices=[('Закрытая охраняемая', 'Закрытая охраняемая'), ('Закрытая', 'Закрытая'), ('Открытая', 'Открытая')], max_length=100)),
                ('sea_destination_m', models.PositiveIntegerField()),
                ('ceiling_height_m', models.PositiveIntegerField()),
                ('gas', models.BooleanField(default=False)),
                ('heating', models.CharField(choices=[('Центральное', 'Центральное'), ('Автономное', 'Автономное'), ('Альтернативное', 'Альтернативное')], max_length=100)),
                ('electricity', models.BooleanField(default=False)),
                ('water_supply', models.CharField(choices=[('Центральное', 'Центральное'), ('Альтернативное', 'Альтернативное')], max_length=100)),
                ('sewerage', models.CharField(choices=[('Центральная', 'Центральная'), ('Альтернативная', 'Альтернативная')], max_length=100)),
                ('registration_type', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('Ипотека', 'Ипотека'), ('Мат.капитал', 'Мат.капитал'), ('Другое', 'Другое')], max_length=200)),
                ('payment_target', models.CharField(max_length=100)),
                ('price_in_contract', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('benefit', models.ManyToManyField(to='builder.benefit')),
            ],
            options={
                'db_table': 'complex',
            },
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.complex')),
            ],
            options={
                'db_table': 'corp',
            },
        ),
        migrations.CreateModel(
            name='DocKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'doc_kit',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='Sewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.complex')),
            ],
            options={
                'db_table': 'sewer',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.corp')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=admin.utils.get_timestamp_path)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='builder.gallery')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('date_published', models.DateField(auto_now_add=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.complex')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('scheme', models.ImageField(upload_to=admin.utils.get_timestamp_path)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.corp')),
            ],
            options={
                'db_table': 'floor',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('scheme', models.ImageField(upload_to=admin.utils.get_timestamp_path)),
                ('square', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('price_per_m2', models.PositiveIntegerField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.floor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.section')),
                ('sewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.sewer')),
            ],
            options={
                'db_table': 'flat',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=admin.utils.get_timestamp_path)),
                ('dock_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_set', to='builder.dockit')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
