# Generated by Django 4.2.3 on 2023-08-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='builder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complex', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complex',
            name='doc_kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.dockit'),
        ),
        migrations.AddField(
            model_name='complex',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complex', to='builder.gallery'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='complex',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefit', to='builder.complex'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.complex'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.floor'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.section'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='sewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.sewer'),
        ),
    ]
