# Generated by Django 4.2.3 on 2023-08-20 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='builder.complex'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='builder.floor'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='builder.section'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='builder.sewer'),
        ),
    ]
