# Generated by Django 4.2.3 on 2023-09-16 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
