# Generated by Django 4.2.3 on 2023-08-15 15:13

import admin.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='address',
            field=models.TextField(default='не указано'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='builder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complex', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complex',
            name='ceiling_height_m',
            field=models.PositiveIntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='coordinate',
            field=models.TextField(default='не указано'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='description',
            field=models.TextField(default='не указано'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='doc_kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.dockit'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.gallery'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='heating',
            field=models.CharField(choices=[('Центральное', 'Центральное'), ('Автономное', 'Автономное'), ('Альтернативное', 'Альтернативное')], default='Центральное', max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='level',
            field=models.CharField(choices=[('Элитный', 'Элитный'), ('Средний', 'Средний'), ('Стандарт', 'Стандарт')], default='Стандарт', max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='main_photo',
            field=models.ImageField(null=True, upload_to=admin.utils.get_timestamp_path),
        ),
        migrations.AlterField(
            model_name='complex',
            name='material_type',
            field=models.CharField(choices=[('Монолитный каркас с керамзитно-блочным заполнением', 'Monolith'), ('Каркасно-панельное', 'Каркасно-панельное строительство'), ('Монолитно-панельное', 'Монолитно-панельное')], default='Монолитно-панельное', max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='max_squares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='min_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='min_squares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='payment_target',
            field=models.CharField(default='не указано', max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='payment_type',
            field=models.CharField(choices=[('Ипотека', 'Ипотека'), ('Мат.капитал', 'Мат.капитал'), ('Другое', 'Другое')], default='Мат.капитал', max_length=200),
        ),
        migrations.AlterField(
            model_name='complex',
            name='perimeter_status',
            field=models.CharField(choices=[('Закрытая охраняемая', 'Закрытая охраняемая'), ('Закрытая', 'Закрытая'), ('Открытая', 'Открытая')], default='Закрытая', max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='price_in_contract',
            field=models.CharField(default='не указано', max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='price_per_square',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='registration_type',
            field=models.CharField(default='не указано', max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='sea_destination_m',
            field=models.PositiveIntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='sewerage',
            field=models.CharField(choices=[('Центральная', 'Центральная'), ('Альтернативная', 'Альтернативная')], default='Центральная', max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='square_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='status',
            field=models.CharField(choices=[('Квартиры', 'Квартиры'), ('Офисы', 'Офисы'), ('Торговые помещения', 'Торговые помещения')], default='Квартиры', max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='title',
            field=models.CharField(default='не указано', max_length=150),
        ),
        migrations.AlterField(
            model_name='complex',
            name='type',
            field=models.CharField(choices=[('Многоквартирный', 'Многоквартирный'), ('Клубный', 'Клубный(Малоквартирный)')], default='Многоквартирный', max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='water_supply',
            field=models.CharField(choices=[('Центральное', 'Центральное'), ('Альтернативное', 'Альтернативное')], default='Центральное', max_length=100),
        ),
    ]
