# Generated by Django 4.2.3 on 2023-08-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_apartment_complex_alter_apartment_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
