# Generated by Django 4.2.3 on 2023-09-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_apartment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together=set(),
        ),
    ]
