# Generated by Django 4.2.3 on 2023-08-21 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0005_apartment_is_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBoardAddingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to_add', to='builder.complex')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chessboard_adding_request',
            },
        ),
    ]
