# Generated by Django 4.2.3 on 2023-08-21 19:25

import admin.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_apartment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_moderated',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='moderation_status',
            field=models.CharField(choices=[('bad_price', 'Некорректная цена'), ('bad_photo', 'Некорректное фото'), ('bad_description', 'Некорректное описание')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='scheme',
            field=models.ImageField(null=True, upload_to=admin.utils.get_timestamp_path),
        ),
    ]
