# Generated by Django 4.2.3 on 2023-08-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_remove_apartment_is_active_apartment_is_moderated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChessBoardAddingRequest',
        ),
    ]
