# Generated by Django 4.2.3 on 2023-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_delete_chessboardaddingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square',
            field=models.IntegerField(default=0),
        ),
    ]
