# Generated by Django 4.2.3 on 2023-08-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_alter_apartment_price_alter_apartment_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
