# Generated by Django 4.2.3 on 2023-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_alter_apartment_price_alter_apartment_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='price_per_m2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
