# Generated by Django 4.2.3 on 2023-08-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_apartment_price_per_m2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='payment_type',
            field=models.CharField(choices=[('', ''), ('Ипотека', 'Ипотека'), ('Мат.капитал', 'Мат.капитал'), ('Другое', 'Другое')], default='Мат.капитал', max_length=200),
        ),
    ]
