# Generated by Django 4.2.3 on 2023-08-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_alter_complex_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='scheme',
            new_name='schema',
        ),
    ]
