# Generated by Django 4.2.3 on 2023-08-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_remove_floor_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex',
            name='doc_kit',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='gallery',
        ),
    ]
