# Generated by Django 4.2.3 on 2023-08-27 11:40

import admin.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0016_remove_complex_doc_kit_remove_complex_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=admin.utils.get_timestamp_path)),
                ('order', models.PositiveIntegerField(default=0)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='builder.complex')),
            ],
            options={
                'db_table': 'gallery_complex',
                'ordering': ('order',),
            },
        ),
    ]
