# Generated by Django 4.2.3 on 2023-08-30 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0019_dockitcomplex_remove_file_dock_kit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='complex',
        ),
        migrations.AddField(
            model_name='complex',
            name='benefit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complex', to='builder.benefit'),
        ),
    ]
