# Generated by Django 4.2.3 on 2023-08-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0020_remove_benefit_complex_complex_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex',
            name='benefit',
        ),
        migrations.AddField(
            model_name='benefit',
            name='complex',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefit', to='builder.complex'),
        ),
    ]
